importacc:
	sui keytool import "tuna pear eye process ordinary satisfy piece twist hill wash butter boy" ed25519
active-address:
	sui client switch --address 0x6cb248bd352582cfb9d2f5c517d954cc64a98d60